Fix Issue with _stepCount Not Resetting, Causing Infinite Separator Exceptions
beto-rodriguez/LiveCharts2 pull request #1535
Opened 2024-06-25 08:52 UTC by airtaxi

### Description:

#### Problem
In the WinUI application, there was an issue where the `_stepCount` variable was not being reset, despite the UI not visibly exceeding 10,000 steps. Over time, `_stepCount` accumulated due to continuous use, which eventually triggered `ThrowInfiniteSeparators()` method calls.

#### Solution
To address this issue, I implemented a change where `_stepCount` is reset to 0 before each logic check that involves this variable.

#### Verification
Post-implementation, the change was tested by monitoring the application for extended periods. The fix proved effective, as the [application](https://github.com/airtaxi/PinStats) no longer threw exceptions after approximately 10 minutes of uptime while showing graphs, a common occurrence prior to this update.

#### Related Issue
This fix also appears to resolve a similar issue reported in [Issue #1076](https://github.com/beto-rodriguez/LiveCharts2/issues/1076#issuecomment-1967245178), further indicating the effectiveness of this solution.

2024-07-20 11:37 UTC, nadav26740 commented
You have added `` _stepCount = 0;`` in every function that ends with             
```cs
if (_stepCount++ > 10000) ThrowInfiniteSeparators();
```
so you could technically just completely remove 
 ```cs
if (_stepCount++ > 10000) ThrowInfiniteSeparators();
```
at functions ``Invalidate``, ``GetPossibleMaxLabelSize``, ``GetPossibleSize``

2024-07-20 11:38 UTC, nadav26740 requested changes
You have added `` _stepCount = 0;`` in every function that ends with             
```cs
if (_stepCount++ > 10000) ThrowInfiniteSeparators();
```
so you could technically just completely remove 
 ```cs
if (_stepCount++ > 10000) ThrowInfiniteSeparators();
```
at the end of functions ``Invalidate``, ``GetPossibleMaxLabelSize``, ``GetPossibleSize``

2024-07-21 15:42 UTC, beto-rodriguez commented
Thanks for the PR @airtaxi 

I think this issue is already fixed with #1514, it will be published in the next version of the library.

2024-07-22 10:49 UTC, airtaxi commented
@beto-rodriguez Thank you for letting me know that issue has already resolved!

I'm glad to hear that.

Therefore, I'm closeing this PR.

2024-07-22 10:49 UTC, closed without merging