Reduce gc allocations on render loop
beto-rodriguez/LiveCharts2 pull request #792
Opened 2022-11-30 13:03 UTC by pkindruk

I have been investigating performance and memory issues on my app recently and mentioned that LiveCharts allocate a lot of single use data on every update. This introduces GC pressure which can be avoided.

I created a test workload to highlight those issues. It has 14x4k LineSeries, 4k FinancialSeries, 150k FinancialSeries and 2 ScatterSeries of 8K points on both. Responsiveness in that setup is really bad. It moves, but has huge lags. Though this story is for another time.

This PR focuses on reducing GC allocation on render loop.

Let's take a look at allocations during render (GC Heap Alloc Ignore Free Stacks). I used PerfView Collect command here, app was already started and data loaded for 10-20 seconds. This highlights what types are being constantly allocated.

![gc-pressure1 0](https://user-images.githubusercontent.com/16784232/204797055-735b3a03-f402-40d2-9801-1f1732f29463.png)

![gc-pressure1 1](https://user-images.githubusercontent.com/16784232/204797056-f3344b57-8595-40c8-be2e-87549de31d61.PNG)

As we can see main allocation sources are:
 - `BezierData`
 - `RectangleHoverArea`
 - `HashSet<ChartPoint>` copy constructor

There is also a tricky case with `float is null`. For some reason JITter doesn't optimize boxing when using launching app using PerfView Run command. This doesn't reproduce on normal start (or at least I can't find evidence). However I need that fix in `MotionProperty<T>` keep recorded performance data clear. JITter should treat `static readonly bool` fields as constants at IL->Asm compilation and simplify comparison.

![gc-pressure1 2](https://user-images.githubusercontent.com/16784232/204797054-4f76721c-4ee0-4a14-8e11-2423f1b1d28b.PNG)

2022-11-30 13:28 UTC, pkindruk commented
Change list:
1. `BezierData` turned to struct. Usage is limited to generator functions and stack of `LineSeries.Invalidate` and `PolarLineSeries.Invalidate` functions. Can probably go further with readonly structs.
2. `ChartPointContext.HoverArea` now initialized lazy.
3. Replaced copy logic for `Series.everFetched`. Now it uses `ChartPoint.RemoveOnCompleted` and counts number points that should be removed.

As for boxing I used approach mentioned in this [StackOverflow question](https://stackoverflow.com/questions/66702734/avoid-boxing-of-is-null).
JITter should treat static readonly bool fields as constants at IL->Asm compilation and simplify comparison.
However issues is probably still present for `Nullable<T>`. But right now there is no evidence, so I skipped it. Currently there are only 2 usages for `MotionProperty<Nullable<T>>`.

With this fix allocations during render look like this:
![gc-pressure2](https://user-images.githubusercontent.com/16784232/204808239-ea7b538a-04ea-46c7-af53-ddae4313986f.PNG)

2022-12-03 03:14 UTC, beto-rodriguez commented
Thanks for profiling the library, your PR is for sure reducing the memory consumption, this is something that will improve for sure the library.

It is smart what you did, I was building a new HashSet containing the points in the UI, it seems that the points are allocated twice with my approach, but your approach is using the current HashSet and just removing the points that were not used, in general your alternative seems smarter.

About the bad performance you faced, I am also working in a high-performance package, it improves 
 drastically how things are render in the UI, you can get a clue [here](https://github.com/beto-rodriguez/LiveCharts2/releases/tag/v2.0.0-beta.350).

There are just a few things that I would like to change, I will commit to this PR to explain the changes.

Thanks this is definitely better.

2022-12-03 03:55 UTC, beto-rodriguez requested changes

2022-12-03 03:55 UTC, beto-rodriguez commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +        var toDeletePoints = points.Where(p => p.RemoveOnCompleted).ToArray();
It seems that it is not necessary to materialize the enumerable, is `ToArray()` required here?

2022-12-03 03:55 UTC, beto-rodriguez commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +        var toDeletePoints = points.Where(p => p.RemoveOnCompleted).ToArray();
> It seems that it is not necessary to materialize the enumerable, is `ToArray()` required here?

Same here

2022-12-03 03:55 UTC, beto-rodriguez commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +    public int ToDeleteCnt { get; private set; }
Maybe `ToDeleteCount` is a better name, also this should probably be private and instead of checking this property in each series, the method should verify the count, if it is zero then we could early return.

I mean, instead of calling this in each series:

```c#
if (toDeletePointsCnt != 0)
            RemoveInvalidPoints(everFetched, cartesianChart.View, primaryScale, secondaryScale, SoftDeleteOrDisposePoint);
```

We could:
```c#
private int _toDeleteCount;

internal static void RemoveInvalidPoints(HashSet<ChartPoint> points, IChartView chartView, Scaler primaryScale, Scaler secondaryScale, Action<ChartPoint, Scaler, Scaler> disposeAction)
{
    if  (_toDeleteCount == 0) return;

    var toDeletePoints = points.Where(p => p.RemoveOnCompleted);
    foreach (var p in toDeletePoints)
    {
        if (p.Context.Chart != chartView) continue;
        disposeAction(p, primaryScale, secondaryScale);
        _ = points.Remove(p);
    }
}
```

Finally on each series only we could remove the `if (toDeletePointsCnt != 0)`

2022-12-03 03:55 UTC, beto-rodriguez commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +        if (point.RemoveOnCompleted) // protect against deleting same point again
We can early return here; it seems easier to read.

Instead of:

```c#
 public void RemovePoint(ChartPoint point)
{
    if (point.RemoveOnCompleted)
    {
        ToDeleteCnt--;
        point.RemoveOnCompleted = false;
    }
}
```

We could do:

```c#
 public void RemovePoint(ChartPoint point)
{
    if (!point.RemoveOnCompleted) return;
    
    ToDeleteCnt--;
    point.RemoveOnCompleted = false;
}
```

2022-12-03 14:57 UTC, beto-rodriguez commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +internal struct ChartPointCleanupContext
It makes more sense to make this object a `class`

2022-12-03 14:58 UTC, beto-rodriguez commented
Those comments summarize the changes I made, thanks again for this PR!

2022-12-03 14:59 UTC, beto-rodriguez approved these changes

2022-12-03 15:00 UTC, merged

2022-12-05 09:49 UTC, pkindruk commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +        var toDeletePoints = points.Where(p => p.RemoveOnCompleted).ToArray();
Generally yes [msdn article](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.enumerator?view=net-7.0#remarks). You better get it back.

But for some reason code below works without exception and expected result on `net5.0` and `net6.0`, but throws on `net472` and `netcoreapp3.1`.
```cs
public class Data
{
    public int Id { get; set; }

    public bool ToRemove { get; set; }
}

static void Main(string[] args)
{
    var set = new HashSet<Data>();

    for (var i = 0; i < 500; i++)
    {
        var removeFlag = i % 2 == 1;
        set.Add(new Data { Id = i, ToRemove = removeFlag });
    }

    var toRemove = set.Where(d => d.ToRemove);
    foreach(var d in toRemove)
    {
        _ = set.Remove(d);
    }

    Console.WriteLine("Success");
    Console.WriteLine(set.Count);
    foreach (var d in set)
        Console.WriteLine(d.Id);
}
```

2022-12-05 09:56 UTC, pkindruk commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +    public int ToDeleteCnt { get; private set; }
Sounds good to me.

2022-12-05 09:57 UTC, pkindruk commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +        if (point.RemoveOnCompleted) // protect against deleting same point again
Sounds good to me.

2022-12-05 10:03 UTC, pkindruk commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +internal struct ChartPointCleanupContext
It is a `struct`, because it is involved only in body of synchronous methods. Allocating it on heap makes no sense, though performance hit will be negligible. If you are afraid of boxing you could make it `ref struct` to get compiler error each time you try to put it on heap.

2022-12-05 14:11 UTC, pkindruk commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +        var toDeletePoints = points.Where(p => p.RemoveOnCompleted).ToArray();
It turned out that this is by design for newer .NET. However we target `netstandard2.0`, so we can't rely on this. There is a `RemoveWhere` method exists since .NET Framework. I propose the following:
```cs
var toDeletePoints = points.Where(p => p.RemoveOnCompleted);//.ToArray();
foreach (var p in toDeletePoints)
{
    if (p.Context.Chart != chartView) continue;
    disposeAction(p, primaryScale, secondaryScale);
    //_ = points.Remove(p);
}
_ = points.RemoveWhere(p => p.RemoveOnCompleted);
```

2022-12-07 02:52 UTC, beto-rodriguez commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +        var toDeletePoints = points.Where(p => p.RemoveOnCompleted).ToArray();
Ok, I might need to revert this.

2022-12-07 02:52 UTC, beto-rodriguez commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +internal struct ChartPointCleanupContext
Ok, got it.

2022-12-07 22:44 UTC, pkindruk commented on src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
> +internal struct ChartPointCleanupContext
I just faced a very tricky bug in my code related to struct copying (someone forgot to use `ref`). I think you are right it is better to stick with `class` here. GC allocations are minimal and harder to mess up.